error: remove the Result type alias
Instead, make a local type alias that can be used within the crate, but
avoid the need to export yet another symbol.